In [1]:
import numpy as np

In [4]:
# Bài 1: Tạo vector 0 với kích thước 10
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Bài 2: Tạo vector 0 nhưng phần tử thứ 5 của vector bằng 1
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [8]:
# Bài 3: Tạo vector với giá trị các phần tử theo thứ tự nằm trong khoảng từ 10 đến 50
# -> là random hay là count từ 10 đến 50 :|
print(np.array(range(10, 51)))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [10]:
# Bài 4: Tạo vector và đảo ngược vector đó
print(np.flip(np.array(range(10, 51))))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
# Bài 5: Tạo ma trận đơn vị kích thước 3x3
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# Bài 6: Tạo ma trận kích thước 3x3 với giá trị các phần tử nguyên ngẫu nhiên
print(np.random.randint(low=1, high=100, size=(3,3)))

[[15 17 67]
 [60 64  3]
 [56 44 17]]


In [26]:
# Bài 7: Tạo ma trận 10x10 với giá trị các phần tử nguyên ngẫu nhiên trong khoảng 1 đến 100
# sau đó tìm giá trị nhỏ nhất và lớn nhất
matrix = np.random.randint(low=1,high=100,size=(10,10))
print(matrix)
size = matrix.shape
max_val = 0
for i in range(0, size[0]):
    for j in range(0, size[1]):
        val = matrix[i, j]
        if (max_val < val):
            max_val = val
print(max_val)

[[36 36 68 79 22 41 71 46 96 63]
 [ 9 79 55 21 88  9 77 73 95 97]
 [91 78 41 73 41 82 81 92 76 53]
 [92 83 98  6 29 69 59 91 95 67]
 [50 42 12 85 54 53 41 57 55 94]
 [94 97 81 93 69 65 74 46 82 27]
 [97  7 21 94 35 81 71 29  7 55]
 [ 7 94 89 59 28 78 81 72 33 66]
 [61 89 57 67 63 40 24  8 14  7]
 [98 24 16 26 81 85 41 32 66 87]]
98


In [34]:
# Bài 8: Tạo một vector kích thước 30 với các giá trị phần tử nguyên ngẫu nhiên trong khoảng 1 đến 100.
# Sau đó tính trung bình
matrix = np.random.randint(low=1,high=100,size=30)
size = matrix.shape
sum = 0
for i in range(0, size[0]):
    sum += matrix[i]
print(sum / size[0])

57.0


In [52]:
# Bài 9: Tạo ma trận 2 chiều với các giá trị các phần tử tại các cạnh
# của ma trận là 1. Các phần tử nằm bên trong bằng 0
matrix = np.array([[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]])
print(matrix)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [61]:
# Bài 10: Cho một ma trận kích thước tùy ý. Thêm border(cạnh viền
# giá trị bằng 0) bao xung quanh ma trận. (Note: Thêm vào chứ không ghì đè)
matrix = np.random.randint(low=1,high=100,size=(5,5))
matrix = np.insert(matrix, 0, 0, axis=1)
matrix = np.insert(matrix, 6, 0, axis=1)
matrix = np.insert(matrix, 0, 0, axis=0)
matrix = np.insert(matrix, 6, 0, axis=0)
print(matrix)

[[ 0  0  0  0  0  0  0]
 [ 0 96 26 54  1 48  0]
 [ 0 36 32 91  5 90  0]
 [ 0 25 37 95 22 71  0]
 [ 0 15 69 91 23 77  0]
 [ 0 65 48 21 69 67  0]
 [ 0  0  0  0  0  0  0]]


In [66]:
# Bài 11: Tạo ma trận 0 kích thước 5x5.Với các phần tử nằm dưới
# đường chéo chính bằng 1, 2, 3, 4
# it's not stupid if it works :|
matrix = np.zeros((5,5))
for i in range(0, 5):
    for j in range(0, 5):
        if i == j + 1:
            matrix[i, j]=i
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [69]:
# Bài 12: Tạo vector kích thước 10 sau đó sắp xếp tăng và giảm dần
vector = np.random.randint(low=1, high=10, size=10)
print(vector)
print(np.sort(vector))
print(np.flip(np.sort(vector)))# IQ 200 :))

[1 8 2 2 5 7 5 4 6 1]
[1 1 2 2 4 5 5 6 7 8]
[8 7 6 5 5 4 2 2 1 1]


In [71]:
# Bài 13: Tạo vector kích thước 10 với giá trị nằm trong khoảng từ 0 đến 1
print(np.random.rand(10))

[0.76613656 0.77499943 0.52320999 0.67916559 0.06984775 0.67550106
 0.76991431 0.4103716  0.08859712 0.13785694]
