In [2]:
import numpy as np

In [3]:
vector1=np.array([1,2,3])
vector1

array([1, 2, 3])

In [4]:
matrix1=np.array([[1,2,3], [4,5,6]])
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
tong=np.sum(matrix1)

In [6]:
tong

21

In [9]:
tong0=np.sum(matrix1, axis=0)
tong0

array([5, 7, 9])