In [2]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv("Data.csv")

In [10]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6      NaN   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
df.isnull().sum()

Country      1
Age          1
Salary       1
Purchased    0
dtype: int64

In [5]:
df = df.dropna(axis=0)

In [6]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6      NaN   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [13]:
# fill nan

from sklearn.impute import SimpleImputer
X=df.values
X[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France', nan,
       'France', 'Germany', 'France'], dtype=object)

In [8]:
# salary
salary_impute = SimpleImputer(np.nan, strategy="mean")
X=df.values
X[:,2]=salary_impute.fit_transform(X[:,2].reshape(-1,1)).ravel()

print(df.isnull().sum())
# age
age_impute = SimpleImputer(np.nan, strategy="mean")
X[:,1]=age_impute.fit_transform(X[:,1].reshape(-1,1)).ravel()

# country
coutry_impute = SimpleImputer(np.nan, strategy="most_frequent")
X[:,0]=coutry_impute.fit_transform(X[:,0].reshape(-1,1)).ravel()

Country      1
Age          1
Salary       1
Purchased    0
dtype: int64


In [27]:
X

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 63777.77777777778, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['France', 38.77777777777778, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [20]:
df.values

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       [nan, nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [28]:
# convert text -> number

from sklearn.preprocessing import LabelEncoder

In [29]:
purchased_label_encoder = LabelEncoder()
X[:,-1]=purchased_label_encoder.fit_transform(X[:,-1])

In [30]:
X

array([['France', 44.0, 72000.0, 0],
       ['Spain', 27.0, 48000.0, 1],
       ['Germany', 30.0, 54000.0, 0],
       ['Spain', 38.0, 61000.0, 0],
       ['Germany', 40.0, 63777.77777777778, 1],
       ['France', 35.0, 58000.0, 1],
       ['France', 38.77777777777778, 52000.0, 0],
       ['France', 48.0, 79000.0, 1],
       ['Germany', 50.0, 83000.0, 0],
       ['France', 37.0, 67000.0, 1]], dtype=object)

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
country_onehot = OneHotEncoder()
temp=country_onehot.fit_transform(X[:,0].reshape(-1,1)).toarray()
X=np.concatenate((temp, X), axis=1)


In [56]:
X=np.delete(X, 3, axis=1)
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0, 'No'],
       [0.0, 0.0, 1.0, 27.0, 48000.0, 'Yes'],
       [0.0, 1.0, 0.0, 30.0, 54000.0, 'No'],
       [0.0, 0.0, 1.0, 38.0, 61000.0, 'No'],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778, 'Yes'],
       [1.0, 0.0, 0.0, 35.0, 58000.0, 'Yes'],
       [1.0, 0.0, 0.0, 38.77777777777778, 52000.0, 'No'],
       [1.0, 0.0, 0.0, 48.0, 79000.0, 'Yes'],
       [0.0, 1.0, 0.0, 50.0, 83000.0, 'No'],
       [1.0, 0.0, 0.0, 37.0, 67000.0, 'Yes']], dtype=object)

In [57]:
# chuan hoa mien gia tri
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [60]:
standard_scaler=StandardScaler()
X[:,4]=standard_scaler.fit_transform(X[:,4].reshape(-1,1)).ravel()
X[:,4]

array([0.7494732544921673, -1.4381784072687536, -0.8912654918285233,
       -0.2532004238149215, 1.7709863242942932e-16, -0.5266568815350365,
       -1.0735697969752667, 1.387538322505769, 1.7521469327992554,
       0.29371249162530866], dtype=object)

In [59]:
minmax_scaler=MinMaxScaler()
X[:,4]=minmax_scaler.fit_transform(X[:,4].reshape(-1,1)).ravel()
X[:,4]

array([0.6857142857142857, 0.0, 0.17142857142857143, 0.3714285714285714,
       0.45079365079365086, 0.2857142857142857, 0.11428571428571432,
       0.8857142857142857, 0.9999999999999999, 0.5428571428571428],
      dtype=object)

In [65]:
# chia du lieu train/test
from sklearn.model_selection import train_test_split
features=X[:, 0:-1]
labels=X[:,-1]
X_train,X_test,y_train,y_test=train_test_split(features, labels, test_size=0.2)
print(X)
print(X_train)
print(X_test)

[[1.0 0.0 0.0 44.0 0.7494732544921673 'No']
 [0.0 0.0 1.0 27.0 -1.4381784072687536 'Yes']
 [0.0 1.0 0.0 30.0 -0.8912654918285233 'No']
 [0.0 0.0 1.0 38.0 -0.2532004238149215 'No']
 [0.0 1.0 0.0 40.0 1.7709863242942932e-16 'Yes']
 [1.0 0.0 0.0 35.0 -0.5266568815350365 'Yes']
 [1.0 0.0 0.0 38.77777777777778 -1.0735697969752667 'No']
 [1.0 0.0 0.0 48.0 1.387538322505769 'Yes']
 [0.0 1.0 0.0 50.0 1.7521469327992554 'No']
 [1.0 0.0 0.0 37.0 0.29371249162530866 'Yes']]
[[1.0 0.0 0.0 37.0 0.29371249162530866]
 [0.0 1.0 0.0 30.0 -0.8912654918285233]
 [0.0 1.0 0.0 50.0 1.7521469327992554]
 [1.0 0.0 0.0 38.77777777777778 -1.0735697969752667]
 [0.0 0.0 1.0 27.0 -1.4381784072687536]
 [1.0 0.0 0.0 48.0 1.387538322505769]
 [0.0 0.0 1.0 38.0 -0.2532004238149215]
 [1.0 0.0 0.0 35.0 -0.5266568815350365]]
[[0.0 1.0 0.0 40.0 1.7709863242942932e-16]
 [1.0 0.0 0.0 44.0 0.7494732544921673]]
